version: "3.9" # I think this is the docker compose version..
services:
  flasky:
    build: .
    ports:
      - 5000:5000 # flask/gunicorn
      - 5432:5432 # postgres
      #- 6379:6379 # redis; don't need it exposed since docker compose creates a network
      - 9201:9200 # elasticsearch; this is local
    command: sh -c "flask run"
    volumes:
      - .:/flasky
    depends_on:
      - redis-server
#      - elasticsearch
  redis-server:
    image: redis:latest
    ports:
      - 6379:6379
  rq-worker:
    build: .
    ports:
      - 8000:5432 # Mapping Docker port 8000 to local port 5432 postgres
    entrypoint: sh -c "rq worker -u redis://redis-server:6379/0 flasky-tasks"
    volumes:
      - ./:/flasky
    depends_on:
      - redis-server
#  elasticsearch: # had issues with max memory, reverted back to local service for use
#    image: elasticsearch:7.8.0
#    ports:
#      - "9200:9200"