"""new fields in user model

Revision ID: 4febae0ee8b5
Revises: 95ee4ee43e81
Create Date: 2023-04-01 20:01:59.359750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4febae0ee8b5"
down_revision = "95ee4ee43e81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("about_me", sa.VARCHAR(length=140), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "last_seen",
                postgresql.TIMESTAMP(timezone=True),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("last_seen")
        batch_op.drop_column("about_me")

    # ### end Alembic commands ###
