"""empty message

Revision ID: 95ee4ee43e81
Revises: e2d1ec55100f
Create Date: 2023-03-22 20:20:18.296602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "95ee4ee43e81"
down_revision = "e2d1ec55100f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=postgresql.BIT(length=32),
            type_=sa.VARCHAR(length=128),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.VARCHAR(length=128),
            type_=postgresql.BIT(length=32),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
