"""adding in followers table

Revision ID: 6af460a86097
Revises: 4febae0ee8b5
Create Date: 2023-04-04 19:32:42.840431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af460a86097'
down_revision = '4febae0ee8b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.user_id'], name=op.f('fk_followers_followed_id_users')),
    sa.ForeignKeyConstraint(['follower_id'], ['users.user_id'], name=op.f('fk_followers_follower_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
