name: Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Install dependencies
           run: | 
            pip install --upgrade pip
            pip install -r requirements.txt

         - name: Run tests
           run: pytest -v -l --junitxml=tests/reports/junit-{datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.xml

         - name: Upload test results
           uses: actions/upload-artifact@v2
           with:
            name: test-results
            path: tests/reports/junit-{datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.xml